### PR TITLE
add follow capabilities to debug mode

### PR DESCRIPTION
**Pull request by ag91**
Fixes https://github.com/ubolonton/emacs-tree-sitter/issues/115

Actually this is my first attempt: I would be happy to get some feedback because this is the first time I implement the follow functionality.

### CODE REVIEW

**Comment by ag91** [comment]
@ubolonton mmm, I guess we can skip this contribution :P Thanks for the amazing work!

**Comment by sogaiu** [comment]
@ag91 I was interested in this but I confess that I didn't feel I understood enough to comment on it in detail.

**Comment by ag91** [comment]
The aim was to jump from the debug tree node to the file element. 
The mechanism is sound because I use it in https://github.com/ag91/moldable-emacs (see video).
I just thought that the PR went stale so if the maintainer finds it useful we can chat later ;)


https://user-images.githubusercontent.com/6580039/129642956-eb1fb07e-8fee-42b1-b688-37c64af8b132.mp4

**Comment by sogaiu** [comment]
Thanks for the demo -- the "follow" functionality does seem nice indeed!

**Comment by ubolonton** [comment]
Sorry I wasn't able to check this out earlier, as I was busy with life until recently.

I just tried this out and couldn't make it work. Maybe it's due to recent changes in `tree-sitter-debug`.

I think the functionality should follow common conventions for similar functionalities in other packages (e.g. putting it behind a minor mode, using established key bindings like `C-c C-f`, `M-n`, `M-p`).

Implementation wise, we should probably imitate, or build on top of `next-error-follow-minor-mode`. (`rg-mode` is a good example.)

**Comment by andno037** [comment]
Hi, what is the outcome of this? And if anybody knows that the discussion/work has been continued somewhere else, I am also interested to know if there has been work for other tree-sitter grammars not only elips.

**Pull request closed without merging**
